basePath: /
host: ws-deviwlndr-59b3a0157dd7.herokuapp.com
info:
  contact:
    email: 714220054@std.ulbi.ac.id
    name: API Support
    url: https://github.com/deviwlndr
  description: This is a sample swagger for Fiber
  title: TES SWAGGER ULBI
  version: "1.0"
paths: {}
schemes:
- https
- http
swagger: "2.0"
